apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: {{ .Values.namespace.name }}
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: techtrends:latest
        name: {{ .Values.namespace.name }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      ports:
      - containerPort: 3111
        protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3111
      readinessProbe:
        httpGet:
          path: /healthz
          port: 3111
status: {}