namespace:
  name: staging

service:
  port: 3111
  protocol: TCP
  type: ClusterIP

replicaCount: 3

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
    
containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111

readinessProbe:
  httpGet:
    path: /healthz
    port: 3111