apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: yusufalma/techtrends:v1.0.0 
        imagePullPolicy: IfNotPresent
        name: python-helloworld
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
